export const externalLinks = {
    m365CopilotApp: "https://x.com/copilot/",
    harmonicVisualizer: "https://davidisrawi.github.io/harmonic-visualizer/",
    mlsAnalytics: "http://mlsanalytics.surge.sh/",
    instagram: "https://www.instagram.com/davidisrawi/",
    superSmashProfile: "https://www.supermajor.gg/ultimate/player/Dahveed?id=S1805146",
    strava: "https://www.strava.com/athletes/125204347",
    resume: "https://drive.google.com/file/d/0BxHec4yAhjE_TExsYjlRbUcyLVU/view?usp=sharing&resourcekey=0-XjRa57thfhaPssVyodLjjQ",
    outfluenzaRepo: "https://github.com/cancanf3/outfluenza",
    outfluenzaDevpost: "https://devpost.com/software/outfluenza-xmtew3",
    allTheFeelsRepo: "https://github.com/DavidIsrawi/AllTheFeels",
    allTheFeelsDevpost: "https://devpost.com/software/allthefeels-9mdqs8",
    summarizeMeRepo: "https://github.com/DavidIsrawi/SummarizeMe",
    summarizeMeSite: "http://summarizeme.surge.sh/",
    flavoredNewsRepo: "https://github.com/JoshuaKoh/LaCodingGranja_2016",
    flavoredNewsDevpost: "https://devpost.com/software/lacodinggranja_2016",
    secureWebsiteArticle: "https://dev.to/davidisrawi/securing-your-website-in-4-minutes---what-why-and-how-of-https-3kcm",
    summarizerArticle: "https://dev.to/davidisrawi/build-a-quick-summarizer-with-python-and-nltk",
    salariesMlsRepo: "https://github.com/DavidIsrawi/SalariesMLS",
    salariesMlsVisualsRepo: "https://github.com/DavidIsrawi/SalariesMLS-Visuals",
    twitchChannel: "https://www.twitch.tv/dahveed_iy"
} as const;
